Vibs\EvesymBundle\Entity\Certmasteries:
    type: entity
    table: certMasteries
    indexes:
        typeID:
            columns:
                - typeID
        certID:
            columns:
                - certID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        masterylevel:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: masteryLevel
    manyToOne:
        typeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                typeID:
                    referencedColumnName: typeID
            orphanRemoval: false
        certid:
            targetEntity: Certcerts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                certID:
                    referencedColumnName: certID
            orphanRemoval: false
    lifecycleCallbacks: {  }
