Vibs\EvesymBundle\Entity\Certskills:
    type: entity
    table: certSkills
    indexes:
        ix_certSkills_skillID:
            columns:
                - skillID
        certID:
            columns:
                - certID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        certlevelint:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: certLevelInt
        skilllevel:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: skillLevel
        certleveltext:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: certLevelText
    manyToOne:
        skillid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                skillID:
                    referencedColumnName: typeID
            orphanRemoval: false
        certid:
            targetEntity: Certcerts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                certID:
                    referencedColumnName: certID
            orphanRemoval: false
    lifecycleCallbacks: {  }
