Vibs\EvesymBundle\Entity\Certcerts:
    type: entity
    table: certCerts
    indexes:
        groupID:
            columns:
                - groupID
    id:
        certid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: certID
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        groupid:
            targetEntity: Invgroups
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                groupID:
                    referencedColumnName: groupID
            orphanRemoval: false
    lifecycleCallbacks: {  }
