Vibs\EvesymBundle\Entity\Crpnpccorporationtrades:
    type: entity
    table: crpNPCCorporationTrades
    indexes:
        corporationID:
            columns:
                - corporationID
        typeID:
            columns:
                - typeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        corporationid:
            targetEntity: Crpnpccorporations
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                corporationID:
                    referencedColumnName: corporationID
            orphanRemoval: false
        typeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                typeID:
                    referencedColumnName: typeID
            orphanRemoval: false
    lifecycleCallbacks: {  }
