Vibs\EvesymBundle\Entity\Dgmtypeattributes:
    type: entity
    table: dgmTypeAttributes
    indexes:
        ix_dgmTypeAttributes_attributeID:
            columns:
                - attributeID
        typeID:
            columns:
                - typeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valueint:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: valueInt
        valuefloat:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: valueFloat
    manyToOne:
        attributeid:
            targetEntity: Dgmattributetypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                attributeID:
                    referencedColumnName: attributeID
            orphanRemoval: false
        typeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                typeID:
                    referencedColumnName: typeID
            orphanRemoval: false
    lifecycleCallbacks: {  }
