Vibs\EvesymBundle\Entity\Industryactivitymaterials:
    type: entity
    table: industryActivityMaterials
    indexes:
        industryActivityMaterials_idx1:
            columns:
                - typeID
                - activityID
        ix_industryActivityMaterials_typeID:
            columns:
                - typeID
        activityID:
            columns:
                - activityID
        materialTypeID:
            columns:
                - materialTypeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        typeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                typeID:
                    referencedColumnName: typeID
            orphanRemoval: false
        activityid:
            targetEntity: Ramactivities
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                activityID:
                    referencedColumnName: activityID
            orphanRemoval: false
        materialtypeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                materialTypeID:
                    referencedColumnName: typeID
            orphanRemoval: false
    lifecycleCallbacks: {  }
