Vibs\EvesymBundle\Entity\Industryblueprints:
    type: entity
    table: industryBlueprints
    indexes:
        typeID:
            columns:
                - typeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        maxproductionlimit:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: maxProductionLimit
    manyToOne:
        typeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                typeID:
                    referencedColumnName: typeID
            orphanRemoval: false
    lifecycleCallbacks: {  }
