Vibs\EvesymBundle\Entity\Invmetatypes:
    type: entity
    table: invMetaTypes
    indexes:
        parentTypeID:
            columns:
                - parentTypeID
        metaGroupID:
            columns:
                - metaGroupID
        typeID:
            columns:
                - typeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        typeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                typeID:
                    referencedColumnName: typeID
            orphanRemoval: false
        parenttypeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                parentTypeID:
                    referencedColumnName: typeID
            orphanRemoval: false
        metagroupid:
            targetEntity: Invmetagroups
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                metaGroupID:
                    referencedColumnName: metaGroupID
            orphanRemoval: false
    lifecycleCallbacks: {  }
