Vibs\EvesymBundle\Entity\Invpositions:
    type: entity
    table: invPositions
    indexes:
        itemID:
            columns:
                - itemID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        x:
            type: float
            nullable: false
            precision: 10
            scale: 0
        'y':
            type: float
            nullable: false
            precision: 10
            scale: 0
        z:
            type: float
            nullable: false
            precision: 10
            scale: 0
        yaw:
            type: float
            nullable: true
            precision: 10
            scale: 0
        pitch:
            type: float
            nullable: true
            precision: 10
            scale: 0
        roll:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        itemid:
            targetEntity: Invnames
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                itemID:
                    referencedColumnName: itemID
            orphanRemoval: false
    lifecycleCallbacks: {  }
