Vibs\EvesymBundle\Entity\Maplocationscenes:
    type: entity
    table: mapLocationScenes
    indexes:
        graphicID:
            columns:
                - graphicID
        locationID:
            columns:
                - locationID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        graphicid:
            targetEntity: Evegraphics
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                graphicID:
                    referencedColumnName: graphicID
            orphanRemoval: false
        locationid:
            targetEntity: Mapregions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                locationID:
                    referencedColumnName: regionID
            orphanRemoval: false
    lifecycleCallbacks: {  }
