Vibs\EvesymBundle\Entity\Mapregions:
    type: entity
    table: mapRegions
    indexes:
        factionID:
            columns:
                - factionID
    id:
        regionid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: regionID
            generator:
                strategy: IDENTITY
    fields:
        regionname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: regionName
        x:
            type: float
            nullable: true
            precision: 10
            scale: 0
        'y':
            type: float
            nullable: true
            precision: 10
            scale: 0
        z:
            type: float
            nullable: true
            precision: 10
            scale: 0
        xmin:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: xMin
        xmax:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: xMax
        ymin:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: yMin
        ymax:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: yMax
        zmin:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: zMin
        zmax:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: zMax
        radius:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        factionid:
            targetEntity: Chrfactions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                factionID:
                    referencedColumnName: factionID
            orphanRemoval: false
    lifecycleCallbacks: {  }
