Vibs\EvesymBundle\Entity\Mapsolarsystems:
    type: entity
    table: mapSolarSystems
    indexes:
        ix_mapSolarSystems_constellationID:
            columns:
                - constellationID
        ix_mapSolarSystems_regionID:
            columns:
                - regionID
        ix_mapSolarSystems_security:
            columns:
                - security
        factionID:
            columns:
                - factionID
        sunTypeID:
            columns:
                - sunTypeID
    id:
        solarsystemid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: solarSystemID
            generator:
                strategy: IDENTITY
    fields:
        solarsystemname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: solarSystemName
        x:
            type: float
            nullable: true
            precision: 10
            scale: 0
        'y':
            type: float
            nullable: true
            precision: 10
            scale: 0
        z:
            type: float
            nullable: true
            precision: 10
            scale: 0
        xmin:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: xMin
        xmax:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: xMax
        ymin:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: yMin
        ymax:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: yMax
        zmin:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: zMin
        zmax:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: zMax
        luminosity:
            type: float
            nullable: true
            precision: 10
            scale: 0
        border:
            type: boolean
            nullable: true
        fringe:
            type: boolean
            nullable: true
        corridor:
            type: boolean
            nullable: true
        hub:
            type: boolean
            nullable: true
        international:
            type: boolean
            nullable: true
        regional:
            type: boolean
            nullable: true
        constellation:
            type: boolean
            nullable: true
        security:
            type: float
            nullable: true
            precision: 10
            scale: 0
        radius:
            type: float
            nullable: true
            precision: 10
            scale: 0
        securityclass:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: securityClass
    manyToOne:
        regionid:
            targetEntity: Mapregions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                regionID:
                    referencedColumnName: regionID
            orphanRemoval: false
        constellationid:
            targetEntity: Mapconstellations
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                constellationID:
                    referencedColumnName: constellationID
            orphanRemoval: false
        factionid:
            targetEntity: Chrfactions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                factionID:
                    referencedColumnName: factionID
            orphanRemoval: false
        suntypeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sunTypeID:
                    referencedColumnName: typeID
            orphanRemoval: false
    lifecycleCallbacks: {  }
