Vibs\EvesymBundle\Entity\Planetschematics:
    type: entity
    table: planetSchematics
    id:
        schematicid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: schematicID
            generator:
                strategy: IDENTITY
    fields:
        schematicname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: schematicName
        cycletime:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cycleTime
    lifecycleCallbacks: {  }
