Vibs\EvesymBundle\Entity\Ramassemblylinestations:
    type: entity
    table: ramAssemblyLineStations
    indexes:
        ix_ramAssemblyLineStations_ownerID:
            columns:
                - ownerID
        ix_ramAssemblyLineStations_solarSystemID:
            columns:
                - solarSystemID
        ix_ramAssemblyLineStations_regionID:
            columns:
                - regionID
        stationID:
            columns:
                - stationID
        assemblyLineTypeID:
            columns:
                - assemblyLineTypeID
        stationTypeID:
            columns:
                - stationTypeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        stationid:
            targetEntity: Stastations
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                stationID:
                    referencedColumnName: stationID
            orphanRemoval: false
        assemblylinetypeid:
            targetEntity: Ramassemblylinetypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                assemblyLineTypeID:
                    referencedColumnName: assemblyLineTypeID
            orphanRemoval: false
        stationtypeid:
            targetEntity: Stastationtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                stationTypeID:
                    referencedColumnName: stationTypeID
            orphanRemoval: false
        solarsystemid:
            targetEntity: Mapsolarsystems
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                solarSystemID:
                    referencedColumnName: solarSystemID
            orphanRemoval: false
        regionid:
            targetEntity: Mapregions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                regionID:
                    referencedColumnName: regionID
            orphanRemoval: false
        ownerid:
            targetEntity: Crpnpccorporations
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ownerID:
                    referencedColumnName: corporationID
            orphanRemoval: false
    lifecycleCallbacks: {  }
