Vibs\EvesymBundle\Entity\Ramassemblylinetypedetailpergroup:
    type: entity
    table: ramAssemblyLineTypeDetailPerGroup
    indexes:
        assemblyLineTypeID:
            columns:
                - assemblyLineTypeID
        groupID:
            columns:
                - groupID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        timemultiplier:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: timeMultiplier
        materialmultiplier:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: materialMultiplier
        costmultiplier:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: costMultiplier
    manyToOne:
        assemblylinetypeid:
            targetEntity: Ramassemblylinetypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                assemblyLineTypeID:
                    referencedColumnName: assemblyLineTypeID
            orphanRemoval: false
        groupid:
            targetEntity: Invgroups
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                groupID:
                    referencedColumnName: groupID
            orphanRemoval: false
    lifecycleCallbacks: {  }
