Vibs\EvesymBundle\Entity\Raminstallationtypecontents:
    type: entity
    table: ramInstallationTypeContents
    indexes:
        installationTypeID:
            columns:
                - installationTypeID
        assemblyLineTypeID:
            columns:
                - assemblyLineTypeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        assemblylinetypeid:
            targetEntity: Ramassemblylinetypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                assemblyLineTypeID:
                    referencedColumnName: assemblyLineTypeID
            orphanRemoval: false
        installationtypeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                installationTypeID:
                    referencedColumnName: typeID
            orphanRemoval: false
    lifecycleCallbacks: {  }
