Vibs\EvesymBundle\Entity\Skinlicense:
    type: entity
    table: skinLicense
    indexes:
        skinID:
            columns:
                - skinID
        licenseTypeID:
            columns:
                - licenseTypeID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        duration:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        licensetypeid:
            targetEntity: Invtypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                licenseTypeID:
                    referencedColumnName: typeID
            orphanRemoval: false
        skinid:
            targetEntity: Skins
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                skinID:
                    referencedColumnName: skinID
            orphanRemoval: false
    lifecycleCallbacks: {  }
