Vibs\EvesymBundle\Entity\Warcombatzonesystems:
    type: entity
    table: warCombatZoneSystems
    indexes:
        combatZoneID:
            columns:
                - combatZoneID
        solarSystemID:
            columns:
                - solarSystemID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        solarsystemid:
            targetEntity: Mapsolarsystems
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                solarSystemID:
                    referencedColumnName: solarSystemID
            orphanRemoval: false
        combatzoneid:
            targetEntity: Warcombatzones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                combatZoneID:
                    referencedColumnName: combatZoneID
            orphanRemoval: false
    lifecycleCallbacks: {  }
